export { default as Avatar } from "./Avatar";
export { default as Display } from "./Display";
export { default as Footer } from "./Footer";
export { default as Form } from "./Form";
export { default as Head } from "./Head";
export { default as Header } from "./Header";
export { default as Input } from "./Input";
export { default as SignIn } from "./Login/signIn";
export { default as SignUp } from "./Login/signUp";
